import type { ColorScheme, InputVariant } from '@vitral/vue';

// The module's options, plus the two pure things it does with them: write the
// file the runtime plugin reads, and work out which components to register.
// Kept out of `module.ts` so they can be tested without a Nuxt instance.

/** The presets `@vitral/vue` ships. Anything else is treated as a module specifier. */
export const presetNames = ['Prism', 'Ink', 'Avalonia', 'Simple', 'Astra'] as const;
export const localeNames = ['en', 'ptBR'] as const;

export type PresetName = (typeof presetNames)[number];
export type LocaleName = (typeof localeNames)[number];

export interface VitralModuleOptions {
    /**
     * A shipped preset by name, a module that default-exports one
     * (`'~/theme/brand'`), or `false` for no theme at all, in which case you
     * bring your own custom properties or go unstyled.
     */
    preset: PresetName | (string & {}) | false;
    /** The scheme to start in. `'system'` follows the operating system. */
    colorScheme: ColorScheme;
    /**
     * The cookie the scheme is remembered in. A cookie rather than
     * localStorage, because the server has to know the scheme to render it.
     * `false` forgets the choice between visits.
     */
    cookie: string | false;
    /** Where the dark scheme applies: a class, an attribute, `'system'`, or `false`. */
    darkModeSelector: string | false;
    /** Wrap the theme and every component's CSS in `@layer <name>`. */
    cssLayer: string | false;
    /** A shipped locale by name, a module that default-exports one, or `false` for the default English. */
    locale: LocaleName | (string & {}) | false;
    inputVariant: InputVariant;
    unstyled: boolean;
    /** Prefix for the registered component names: `'Vt'` gives `<VtButton>`, `''` gives `<Button>`. */
    prefix: string;
    /** Register every component globally. Turn it off to import them by hand. */
    components: boolean;
    /** Auto-import `useTheme()`, `useToast()`, `useForm()` and the rest. */
    composables: boolean;
}

export const defaults: VitralModuleOptions = {
    preset: 'Ink',
    colorScheme: 'system',
    cookie: 'vitral-scheme',
    darkModeSelector: '.vt-dark',
    cssLayer: false,
    locale: 'en',
    inputVariant: 'outlined',
    unstyled: false,
    prefix: 'Vt',
    components: true,
    composables: true
};

/** Composables the manifest misses, because they do not live in the composables folder. */
export const extraComposables = ['useVitral'];

const isName = (names: readonly string[], value: unknown) => typeof value === 'string' && names.includes(value);

/**
 * The module the runtime plugin imports as `#build/vitral-options.mjs`. The
 * preset, locale and directives are objects, and `nuxt.config` carries data, so
 * they are imported here by the name the configuration gave. A bundler then
 * keeps only the ones asked for.
 */
export function optionsTemplate(options: VitralModuleOptions, directives: readonly string[] = []): string {
    const imports: string[] = [];
    const named: string[] = [];

    if (options.preset === false) imports.push('const preset = null;');
    else if (isName(presetNames, options.preset)) named.push(`${options.preset} as preset`);
    else imports.push(`import preset from ${JSON.stringify(options.preset)};`);

    if (options.locale === false) imports.push('const locale = null;');
    else if (isName(localeNames, options.locale)) named.push(`${options.locale} as locale`);
    else imports.push(`import locale from ${JSON.stringify(options.locale)};`);

    // Directives are registered on the app rather than auto-imported. The
    // template compiler decides what `v-tooltip` means before any import
    // transform runs, so an auto-import never reaches it.
    if (directives.length) named.push(...directives);
    if (named.length) imports.unshift(`import { ${named.join(', ')} } from '@vitral/vue';`);

    const runtime = {
        colorScheme: options.colorScheme,
        cookie: options.cookie,
        darkModeSelector: options.darkModeSelector,
        cssLayer: options.cssLayer,
        inputVariant: options.inputVariant,
        unstyled: options.unstyled
    };

    return [
        '// Generated by @vitral/nuxt. Do not edit by hand.',
        '// The options from `nuxt.config`, with the preset and the locale imported',
        '// by name, so the bundler keeps only the ones the application asked for.',
        ...imports,
        '',
        'export { preset, locale };',
        `export const directives = {${directives.map((name) => ` ${name.toLowerCase()}: ${name} `).join(',')}};`,
        `export const options = ${JSON.stringify(runtime, null, 4)};`,
        ''
    ].join('\n');
}

export interface ComponentRegistration {
    name: string;
    export: string;
    filePath: string;
}

/**
 * Every component to register globally, under the configured prefix. None of
 * them is client-only. The chart, which cannot be drawn on a server, still
 * renders its empty host there and fills it on mount, and that hydrates
 * cleanly. Nuxt's client-only wrapper withholds the template until after
 * `mounted`, by which point the chart has no element to draw in.
 */
export function componentRegistrations(names: readonly string[], prefix: string): ComponentRegistration[] {
    return names.map((name) => ({ name: prefix + name, export: name, filePath: '@vitral/vue' }));
}
