// Generated by scripts/gen-index.mjs. Do not edit by hand.
import accordion from './accordion';
import aspectratio from './aspectratio';
import autocomplete from './autocomplete';
import avatar from './avatar';
import avatargroup from './avatargroup';
import badge from './badge';
import blockui from './blockui';
import breadcrumb from './breadcrumb';
import button from './button';
import buttongroup from './buttongroup';
import card from './card';
import carousel from './carousel';
import cascadeselect from './cascadeselect';
import chart from './chart';
import checkbox from './checkbox';
import chip from './chip';
import colorpicker from './colorpicker';
import command from './command';
import confirmdialog from './confirmdialog';
import confirmpopup from './confirmpopup';
import contextmenu from './contextmenu';
import cropper from './cropper';
import datagrid from './datagrid';
import datatable from './datatable';
import dataview from './dataview';
import datepicker from './datepicker';
import daterange from './daterange';
import dialog from './dialog';
import divider from './divider';
import dock from './dock';
import dockpanel from './dockpanel';
import drawer from './drawer';
import dynamicdialog from './dynamicdialog';
import editor from './editor';
import fieldset from './fieldset';
import fileupload from './fileupload';
import floatlabel from './floatlabel';
import form from './form';
import galleria from './galleria';
import grid from './grid';
import hovercard from './hovercard';
import iconfield from './iconfield';
import iftalabel from './iftalabel';
import image from './image';
import inplace from './inplace';
import inputgroup from './inputgroup';
import inputgroupaddon from './inputgroupaddon';
import inputmask from './inputmask';
import inputnumber from './inputnumber';
import inputotp from './inputotp';
import inputpassword from './inputpassword';
import inputtag from './inputtag';
import inputtext from './inputtext';
import knob from './knob';
import label from './label';
import listbox from './listbox';
import megamenu from './megamenu';
import menu from './menu';
import menubar from './menubar';
import message from './message';
import metergroup from './metergroup';
import multiselect from './multiselect';
import orderlist from './orderlist';
import organizationchart from './organizationchart';
import overlaybadge from './overlaybadge';
import paginator from './paginator';
import panel from './panel';
import panelmenu from './panelmenu';
import picklist from './picklist';
import popover from './popover';
import progressbar from './progressbar';
import progressspinner from './progressspinner';
import radiobutton from './radiobutton';
import radiogroup from './radiogroup';
import rating from './rating';
import schedule from './schedule';
import scrollpanel from './scrollpanel';
import scrolltop from './scrolltop';
import select from './select';
import selectbutton from './selectbutton';
import sidebar from './sidebar';
import skeleton from './skeleton';
import slider from './slider';
import speeddial from './speeddial';
import splitbutton from './splitbutton';
import splitter from './splitter';
import splitview from './splitview';
import spreadsheet from './spreadsheet';
import stackpanel from './stackpanel';
import stepper from './stepper';
import tabs from './tabs';
import tag from './tag';
import taskboard from './taskboard';
import terminal from './terminal';
import textarea from './textarea';
import tieredmenu from './tieredmenu';
import timeline from './timeline';
import toast from './toast';
import togglebutton from './togglebutton';
import toggleswitch from './toggleswitch';
import toolbar from './toolbar';
import tooltip from './tooltip';
import tree from './tree';
import treeselect from './treeselect';
import treetable from './treetable';
import uniformgrid from './uniformgrid';
import virtualscroller from './virtualscroller';
import wrappanel from './wrappanel';

export const components = {
    accordion,
    aspectratio,
    autocomplete,
    avatar,
    avatargroup,
    badge,
    blockui,
    breadcrumb,
    button,
    buttongroup,
    card,
    carousel,
    cascadeselect,
    chart,
    checkbox,
    chip,
    colorpicker,
    command,
    confirmdialog,
    confirmpopup,
    contextmenu,
    cropper,
    datagrid,
    datatable,
    dataview,
    datepicker,
    daterange,
    dialog,
    divider,
    dock,
    dockpanel,
    drawer,
    dynamicdialog,
    editor,
    fieldset,
    fileupload,
    floatlabel,
    form,
    galleria,
    grid,
    hovercard,
    iconfield,
    iftalabel,
    image,
    inplace,
    inputgroup,
    inputgroupaddon,
    inputmask,
    inputnumber,
    inputotp,
    inputpassword,
    inputtag,
    inputtext,
    knob,
    label,
    listbox,
    megamenu,
    menu,
    menubar,
    message,
    metergroup,
    multiselect,
    orderlist,
    organizationchart,
    overlaybadge,
    paginator,
    panel,
    panelmenu,
    picklist,
    popover,
    progressbar,
    progressspinner,
    radiobutton,
    radiogroup,
    rating,
    schedule,
    scrollpanel,
    scrolltop,
    select,
    selectbutton,
    sidebar,
    skeleton,
    slider,
    speeddial,
    splitbutton,
    splitter,
    splitview,
    spreadsheet,
    stackpanel,
    stepper,
    tabs,
    tag,
    taskboard,
    terminal,
    textarea,
    tieredmenu,
    timeline,
    toast,
    togglebutton,
    toggleswitch,
    toolbar,
    tooltip,
    tree,
    treeselect,
    treetable,
    uniformgrid,
    virtualscroller,
    wrappanel
};
