#!/usr/bin/env node
// Regenerates every barrel that lists components, so adding a component is
// adding its folders — never editing a shared list by hand. `--check` exits 1
// when a barrel is out of date, which is how CI catches a forgotten run.

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const HEADER = '// Generated by scripts/gen-index.mjs. Do not edit by hand.\n';
let stale = 0;

const dirs = (path) =>
    readdirSync(join(root, path))
        .filter((name) => statSync(join(root, path, name)).isDirectory())
        .sort();

const files = (path, test) =>
    readdirSync(join(root, path))
        .filter((name) => test(name))
        .sort();

function write(file, content) {
    const path = join(root, file);
    if (existsSync(path) && readFileSync(path, 'utf8') === content) return;
    stale++;
    if (check) console.error(`stale: ${file}`);
    else {
        writeFileSync(path, content);
        console.log(`wrote ${file}`);
    }
}

// Component tokens: one file per component, named after the style's `name`.
const tokens = 'packages/themes/src/presets/base/components';
const tokenNames = files(tokens, (f) => f.endsWith('.ts') && f !== 'index.ts').map((f) => f.slice(0, -3));
write(
    `${tokens}/index.ts`,
    `${HEADER}${tokenNames.map((n) => `import ${n} from './${n}';`).join('\n')}\n\nexport const components = {\n${tokenNames.map((n) => `    ${n}`).join(',\n')}\n};\n`
);

// Component styles: one folder per component.
const styles = 'packages/styles/src';
// A folder without its index.ts is still being written; leave it out until it has one.
const styleDirs = dirs(styles).filter((d) => d !== 'base' && existsSync(join(root, styles, d, 'index.ts')));
write(`${styles}/index.ts`, `${HEADER}export * from './defineStyle';\nexport * from './base';\n${styleDirs.map((d) => `export * from './${d}';`).join('\n')}\n`);

// Vue components: one folder per component, each with an index.ts.
const components = 'packages/vue/src/components';
const componentDirs = dirs(components).filter((d) => existsSync(join(root, components, d, 'index.ts')));
write(`${components}/index.ts`, `${HEADER}${componentDirs.map((d) => `export * from './${d}';`).join('\n')}\n`);

// The names a framework integration needs: every component this package
// exports and every composable it offers. The Nuxt module and the unplugin
// resolver register these, and neither can import the package to ask, since
// the source is .vue files. So read them out of the barrels the folders
// already have. `Form` is the one exception: it is a frozen object of parts,
// not a component, because a component named `Form` would clash with `<form>`.
const notComponents = new Set(['Form']);
const componentNames = new Set();
for (const dir of componentDirs) {
    const source = readFileSync(join(root, components, dir, 'index.ts'), 'utf8');
    // `export { default as Button } from './Button.vue'`
    for (const [, name] of source.matchAll(/export \{ default as (\w+) \} from '\.\/[\w.]+\.vue'/g)) componentNames.add(name);
    // An SFC imported under a name and re-exported under it (the compound parts).
    const locals = new Set(Array.from(source.matchAll(/^import (\w+) from '\.\/[\w.]+\.vue';$/gm), (m) => m[1]));
    // One part under a second name: `const FormErrors = FormSummary;`
    for (const [, alias, of] of source.matchAll(/^const (\w+) = (\w+);$/gm)) if (locals.has(of)) locals.add(alias);
    for (const [, list] of source.matchAll(/^export \{([^}]*)\};$/gm)) {
        for (const name of list.split(',').map((n) => n.trim())) if (locals.has(name)) componentNames.add(name);
    }
    // A component built from an SFC and carrying its parts: `export const Editor = …`.
    if (new RegExp(`^export const ${dir} =`, 'm').test(source)) componentNames.add(dir);
}

const composables = 'packages/vue/src/composables';
// A composable can bring a component of its own (`OverlayScope`), which is a
// component like any other to whatever registers them.
for (const file of files(composables, (f) => f.endsWith('.ts') && !f.endsWith('.spec.ts'))) {
    const source = readFileSync(join(root, composables, file), 'utf8');
    for (const [, name] of source.matchAll(/^export const (\w+) = defineComponent\(/gm)) componentNames.add(name);
}

const composableNames = files(composables, (f) => /^use[A-Z].*\.ts$/.test(f) && !f.endsWith('.spec.ts'))
    .map((f) => f.slice(0, -3))
    // The file is named after the composable, but not every one exports it:
    // `useStyle.ts` re-exports the framework-free `loadStyle`.
    .filter((name) => new RegExp(`export (?:async )?(?:function|const) ${name}\\b`).test(readFileSync(join(root, composables, `${name}.ts`), 'utf8')));

// Directives are exported the same way, one file each: `export const Tooltip: Directive`.
const directives = 'packages/vue/src/directives';
const directiveNames = files(directives, (f) => f.endsWith('.ts') && !f.endsWith('.spec.ts') && f !== 'index.ts').flatMap((file) =>
    Array.from(readFileSync(join(root, directives, file), 'utf8').matchAll(/^export const (\w+): Directive/gm), (m) => m[1])
);

write(
    `${components}/manifest.ts`,
    `${HEADER}/**\n * Every component and composable \`@vitral/vue\` exports, by name, for whatever\n * registers them globally (the Nuxt module, the unplugin resolver). Plain data:\n * nothing is imported here, so a build tool can read it.\n */\nexport const componentNames = [\n${Array.from(componentNames)
        .filter((n) => !notComponents.has(n))
        .sort()
        .map((n) => `    '${n}'`)
        .join(',\n')}\n] as const;\n\nexport const composableNames = [\n${composableNames.map((n) => `    '${n}'`).join(',\n')}\n] as const;\n\nexport const directiveNames = [\n${directiveNames.map((n) => `    '${n}'`).join(',\n')}\n] as const;\n`
);

// Composables and directives contributed by components: one file each.
for (const folder of ['packages/vue/src/composables', 'packages/vue/src/directives']) {
    const core = new Set(['index.ts', 'useStyle.ts', 'useTheme.ts', 'useLocale.ts', 'useOverlay.ts', 'useFocusTrap.ts']);
    const names = files(folder, (f) => f.endsWith('.ts') && !f.endsWith('.spec.ts') && !core.has(f)).map((f) => f.slice(0, -3));
    write(`${folder}/index.ts`, `${HEADER}${names.length ? names.map((n) => `export * from './${n}';`).join('\n') : 'export {};'}\n`);
}

// Icons: one file per category. `index.ts` re-exports every icon by name (what
// applications import); `all.ts` gathers them for `@vitral/icons/registry`.
const iconDir = 'packages/icons/src/icons';
const iconSets = files(iconDir, (f) => f.endsWith('.ts') && !f.endsWith('.spec.ts') && f !== 'index.ts' && f !== 'all.ts').map((f) => f.slice(0, -3));
write(`${iconDir}/index.ts`, `${HEADER}${iconSets.map((n) => `export * from './${n}';`).join('\n')}\n`);
write(
    `${iconDir}/all.ts`,
    `${HEADER}${iconSets.map((n) => `import * as ${n} from './${n}';`).join('\n')}\n\n` +
        `/** Every icon file, by category id. */\nexport const sets = { ${iconSets.join(', ')} };\n\n` +
        `/** Every icon, by name. */\nexport const icons = {\n${iconSets.map((n) => `    ...${n}`).join(',\n')}\n};\n`
);

if (check && stale) {
    console.error(`${stale} barrel(s) out of date — run \`pnpm gen\`.`);
    process.exit(1);
}
