#!/usr/bin/env python3
"""Writes packages/core/src/math/glyphs.ts: the outlines formulas are drawn with.

The glyphs come from Noto Sans Math, and from Noto Sans for the accented
letters and the few signs the mathematical font lacks; the layout constants
come from the mathematical font's MATH table. Both fonts are under the SIL Open
Font License 1.1 (packages/core/LICENSE.OFL).

    pip install fonttools
    python3 scripts/math-glyphs.py NotoSansMath-Regular.ttf 'NotoSans[wght].ttf'

Run it when a formula needs a glyph that is not in the file yet (add the
character to "chars" below), then run the specs in packages/core/src/math.
"""
import json, os, sys
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen

if len(sys.argv) != 3:
    sys.exit(__doc__)
math = TTFont(sys.argv[1])
text = TTFont(sys.argv[2])

def glyph(font, name):
    gs = font.getGlyphSet()
    pen = SVGPathPen(gs, ntos=lambda v: str(int(round(v))))
    gs[name].draw(TransformPen(pen, (1, 0, 0, -1, 0, 0)))
    b = BoundsPen(gs); gs[name].draw(b)
    lo, hi = (int(round(b.bounds[1])), int(round(b.bounds[3]))) if b.bounds else (0, 0)
    return [int(round(font['hmtx'][name][0])), lo, hi, pen.getCommands().replace(' -', '-')]

out = {}
mcmap, tcmap = math.getBestCmap(), text.getBestCmap()
chars = [chr(c) for c in range(0x21, 0x7F)]
chars += list('ΓΔΘΛΞΠΣΦΨΩαβγδεζηθικλμνξπρστυφχψω')
chars += [chr(c) for c in range(0x1D434, 0x1D468)] + ['ℎ'] + [chr(c) for c in range(0x1D6FC, 0x1D715)]
chars += list('×÷·±∓∗∪∩≤≥≠≈≡∼∝→←⇒⇔∈∉⊂⊆∞∂∇∀∃∅°…⋯′−∑∏∫√‖⟨⟩')
chars += list('ÀÁÂÃÇÉÊÍÓÔÕÚàáâãçéêíóôõúüñ')
missing = []
for ch in dict.fromkeys(chars):
    cp = ord(ch)
    if cp in mcmap: out[ch] = glyph(math, mcmap[cp])
    elif cp in tcmap: out[ch] = glyph(text, tcmap[cp])
    else: missing.append(ch)
# Taller cuts of the signs that grow: each is its own drawing, not the small one stretched.
variants = math['MATH'].table.MathVariants
cover = variants.VertGlyphCoverage.glyphs
for ch in '()[]{}|√∑∏∫‖⟨⟩':
    name = mcmap[ord(ch)]
    if name not in cover: continue
    records = variants.VertGlyphConstruction[cover.index(name)].MathGlyphVariantRecord
    n = 0
    for record in records:
        if record.VariantGlyph == name: continue
        n += 1
        if n > 7: break
        out[f'{ch}#{n}'] = glyph(math, record.VariantGlyph)
c = math['MATH'].table.MathConstants
val = lambda k: (lambda v: getattr(v, 'Value', v))(getattr(c, k))
metrics = {k[0].lower() + k[1:]: val(k) for k in ['AxisHeight', 'FractionRuleThickness', 'FractionNumeratorShiftUp', 'FractionNumeratorDisplayStyleShiftUp', 'FractionDenominatorShiftDown', 'FractionDenominatorDisplayStyleShiftDown', 'FractionNumeratorGapMin', 'FractionNumDisplayStyleGapMin', 'SuperscriptShiftUp', 'SubscriptShiftDown', 'SuperscriptBaselineDropMax', 'SubscriptBaselineDropMin', 'SubSuperscriptGapMin', 'RadicalRuleThickness', 'RadicalVerticalGap', 'RadicalDisplayStyleVerticalGap', 'RadicalExtraAscender', 'UpperLimitGapMin', 'LowerLimitGapMin', 'OverbarVerticalGap', 'OverbarRuleThickness']}
metrics['xHeight'] = math['OS/2'].sxHeight
print('glyphs', len(out), 'missing', missing, file=sys.stderr)
lines = ['// Generated by scripts/math-glyphs.py: the outlines a formula is drawn with. Do not edit by hand.', '//', '// From Noto Sans Math (Copyright 2022 Google LLC) and Noto Sans (Copyright 2022 The', '// Noto Project Authors), under the SIL Open Font License, Version 1.1: see', '// packages/core/LICENSE.OFL. Each entry is the', "// glyph's advance, its lowest and highest point (y up) and its outline (y down),", '// in thousandths of an em.', '', '/* eslint-disable */', 'export type MathGlyph = readonly [advance: number, low: number, high: number, d: string];', '',
    'export const MATH_METRICS = ' + json.dumps(metrics, indent=4) + ' as const;', '', 'export const MATH_GLYPHS: Record<string, MathGlyph> = {']
for k, v in out.items(): lines.append('    ' + json.dumps(k, ensure_ascii=False) + ': ' + json.dumps(v, ensure_ascii=False, separators=(',', ':')) + ',')
lines.append('};'); lines.append('')
target = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'packages', 'core', 'src', 'math', 'glyphs.ts')
open(target, 'w').write('\n'.join(lines))
