// Generated by scripts/gen-index.mjs — do not edit by hand.
import * as actions from './actions';
import * as arrows from './arrows';
import * as buildings from './buildings';
import * as charts from './charts';
import * as commerce from './commerce';
import * as communication from './communication';
import * as development from './development';
import * as devices from './devices';
import * as education from './education';
import * as files from './files';
import * as finance from './finance';
import * as food from './food';
import * as games from './games';
import * as health from './health';
import * as maps from './maps';
import * as media from './media';
import * as people from './people';
import * as security from './security';
import * as shapes from './shapes';
import * as sports from './sports';
import * as text from './text';
import * as time from './time';
import * as transport from './transport';
import * as weather from './weather';

/** Every icon file, by category id. */
export const sets = { actions, arrows, buildings, charts, commerce, communication, development, devices, education, files, finance, food, games, health, maps, media, people, security, shapes, sports, text, time, transport, weather };

/** Every icon, by name. */
export const icons = {
    ...actions,
    ...arrows,
    ...buildings,
    ...charts,
    ...commerce,
    ...communication,
    ...development,
    ...devices,
    ...education,
    ...files,
    ...finance,
    ...food,
    ...games,
    ...health,
    ...maps,
    ...media,
    ...people,
    ...security,
    ...shapes,
    ...sports,
    ...text,
    ...time,
    ...transport,
    ...weather
};
